### ISSUE TITLE
Local Docker Compose exited abnormally with code 1 whilst running command: up -d

### ISSUE THREAD

**Issue by npersad** [testcontainers/testcontainers-scala#46]
Hello, I am trying to use the DockerComposeContainer but I keep getting the error below:
I verified that docker-compose up -d works locally.

INFO  🐳 [docker-compose] - Local Docker Compose is running command: pull
INFO  🐳 [docker-compose] - Docker Compose has finished running
INFO  🐳 [docker-compose] - Local Docker Compose is running command: up -d

Exception encountered when invoking run on a nested suite - Local Docker Compose exited abnormally with code 1 whilst running command: up -d
org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 1 whilst running command: up -d
	at org.testcontainers.containers.LocalDockerCompose.invoke(DockerComposeContainer.java:656)
	at org.testcontainers.containers.DockerComposeContainer.runWithCompose(DockerComposeContainer.java:216)
compose file
```
version: "2.2"
services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

volumes:
  esdata01:
    driver: local

networks:
  esnet:
```
creating my test container like so
```
  val container = new DockerComposeContainer(new File("elastic-api/src/test/resources/docker-compose.yml"),exposedServices = Seq(
    ExposedService("es01", 9200)
  ))
```
